const esEndings = ["s", "x", "z", "ch", "sh"];

/**
 * Pluralizes a word based on the count provided. Generated by trusty VSCode.
 * @param word The word to pluralize
 * @param count The count to determine pluralization
 * @returns The pluralized form of the word if count is not 1, otherwise returns the original word
 */
export function pluralize(word: string, count: number): string {
  if (count === 1) {
    return word;
  }

  if (word.endsWith("y") && !/[aeiou]y$/i.test(word)) {
    return word.substring(0, word.length - 1) + "ies";
  }

  if (esEndings.some((ending) => word.endsWith(ending))) {
    return word + "es";
  }

  return word + "s";
}
